import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Document App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Document App</a>
        </h1>

        <p className={styles.description}>
          Get started by Joining today
        </p>

        <div className={styles.grid}>
          <a href="/signup" className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Register to store your important documents online for easy access.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>View &rarr;</h2>
            <p>View all your documents!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by
          <span >
            <p>Aaditya Bhardwaj</p>
            <style jsx>{'p {font-weight:600;} span{margin-left:0.6rem}'}</style>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
