import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const SignUp: NextPage = () => {
  let login = "Log in to your account";
  let signup = "SignUp";
  return (
    <div className={styles.background}>
      <div className={styles.container}>
        <Head>
          <title>Log In</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.logcard}>
             <div className={styles.logcont}>
            <p className={styles.login}>{login}</p>
            <form className={styles.formlog}>
                <div className={styles.username}>
                <input id="Username" name ="Username" type="text" placeholder="Username" required></input>
                </div>
                <div className={styles.username}>
                
                <input id="Password" name ="Password" type="password"  placeholder="Password" required></input>
                </div>
                <button type="button" className={styles.signbtn}>Login</button>
            </form>
            </div>
          </div>
        </main>
        <footer className={styles.footer}>
          <a target="_blank" rel="noopener noreferrer">
            Made by
            <span>
              <p>Aaditya Bhardwaj</p>
            </span>
            <style jsx>
              {
                "a {color:white;} p {font-weight:600;color:white} span{margin-left:0.6rem}"
              }
            </style>
          </a>
        </footer>
      </div>
    </div>
  );
};

export default SignUp;
